# Generated by Django 4.1.1 on 2022-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
