# Generated by Django 4.1 on 2022-12-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_article_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='carefory',
            new_name='category',
        ),
    ]
