# Generated by Django 4.1 on 2022-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_carefory_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='category_name', to='blog_app.category'),
        ),
    ]
